### ISSUE TITLE
Contrastive learning

### ISSUE THREAD

**Issue by wjczf123** [Lackel/Hierarchical-Weighted-Self-contrastive-Learning#1]
Hi, wenbin.

I have questions about contrastive learning in Section 3.2.4.

It seems that Eq. (11) uses a bigger \alpha_{diff} to ensure the distance condition (i.e., Eq.(4)).

But what is the meaning of Eq.(12)- Eq.(14)? I'm a little confused. For example, where is '+ 1/T' come from in Eq. (12)?

**Comment by wjczf123** [comment]
I am looking forward to your reply. Thanks.

**Comment by Lackel** [comment]
Hi, thank you for your interest in our work. 
We perform gradient analysis in Eq.(12)- Eq.(14). And the gradients of our loss towards the positive similarity  $sim(h_{i}^{o}, h_{i}^{L})$ and negative similarity $sim(h_{i}^{o}, h_{j}^{o}) ( i\neq j)$ are shown below.
![image](https://user-images.githubusercontent.com/39994881/234226283-8384e4d2-d7e0-4149-8812-c61b3bc0f57a.png)
So according to the gradient descent algorithm, the positive similarity  and negative similarity will be updated as in the Eq.(12) and Eq.(13).

**Comment by wjczf123** [comment]
Thanks for your reply. I got it.

**Comment by wjczf123** [comment]
The gradinets of positive similarity seems to be \sum \alpha_{l} P_{i,j}. I'm not sure that's correct.

**Comment by Lackel** [comment]
Hi. We only have  positive similarity in the numerator, which equals to $-sim/\tau$.

**Comment by wjczf123** [comment]
Thanks. I get it. But why is there no sim(h_i^o, h_i^L) in the denominator? Is there any particular reason or motivation?

**Comment by Lackel** [comment]
Actually it is only for simplicity because it is difficult to decide the relative weights between positive and negative similarities in the denominator. We also tried the weight 1 for positive similarity in the denominator but the results were not good, so we just dropped it.

**Comment by wjczf123** [comment]
Thanks for your detailed reply. Best wishes.

**Comment by wjczf123** [comment]
你好，wenbin。非常抱歉再次打扰。我还有一个问题关于weight机制。

weight机制是否只能使不同粗类的梯度更大，相较于不使用weight机制。而无法保证d_{fine} < d_{coarse}。
因为每轮的梯度不仅和weight相关，还跟相似度有关。尤其相似度除以了温度并且经过了exp，可能对最终的梯度影响会更大。

不过，我也承认weight机制是理论有效的。不过从目前的推导好像无法得出d_{fine} < d_{coarse}这一结论。

**Comment by Lackel** [comment]
您好，很抱歉年底工作忙导致这么久才回复。
正如您所说的，weight机制就是为了避免相似度不同带来的梯度大小的问题，因此只要调整合适的权重，是可以保证d_{fine} < d_{coarse}的。虽然相似度除以了温度并且经过了exp，但是其需要除归一化常数（公式14），因此值的差距不会特别大。另外，由于我们在训练时有粗粒度标签，因此最简单的方式就是根据公式计算出粗粒度内/粗粒度间的相似度的值，然后根据这个值调节权重的大小。
希望以上的回答对您有帮助。

**Comment by wjczf123** [comment]
非常感谢您的帮助，我明白了。希望您工作生活顺利。
